### ISSUE TITLE
Can't compile with zlib 1.2.6

### ISSUE THREAD

**Issue by miguellopes** [rieck/sally#2]
Hey, I'm getting the following errors compiling sally with zlib 1.2.6, i believe the problem is that with the new version of zlib gzFile is now a struct:
-typedef voidp gzFile;       /\* opaque gzip file descriptor _/
+typedef struct gzFile_s *gzFile;    /_ semi-opaque gzip file descriptor */

input_lines.c: In function 'input_lines_open':
input_lines.c:82: warning: assignment from incompatible pointer type
input_lines.c:98: error: request for member 'have' in something not a structure or union
input_lines.c:98: error: request for member 'have' in something not a structure or union
input_lines.c:98: error: request for member 'pos' in something not a structure or union
input_lines.c:98: warning: left-hand operand of comma expression has no effect
input_lines.c:98: error: request for member 'next' in something not a structure or union
input_lines.c:98: warning: left-hand operand of comma expression has no effect
input_lines.c:98: warning: passing argument 1 of 'gzgetc_' from incompatible pointer type
input_lines.c:104: warning: passing argument 1 of 'gzrewind' from incompatible pointer type
input_lines.c: In function 'input_lines_close':
input_lines.c:154: warning: passing argument 1 of 'gzclose' from incompatible pointer type

My C is just too much rusty to fix this on my own, i got it to compile but when i try to use sally i get a Segmentation Fault...
